version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: otter
      POSTGRES_USER: otter
      POSTGRES_PASSWORD: otter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
